### PR TITLE
Debian section for deb support.

### PR DESCRIPTION
**Pull request by tonyskapunk**

### CODE REVIEW

**Comment by thebwt** [comment]
Needs a changelog

**Comment by thebwt** [comment]
makefiles (debian/rules) needs to use tabs, not spaces for indentation.

**Comment by thebwt** [comment]
python-setuptools is a  build requirement

**Comment by thebwt** [comment]
with all that done, here's the package I get.
[kthresher_1.2.2_all.deb.gz](https://github.com/rackerlabs/kthresher/files/228607/kthresher_1.2.2_all.deb.gz)

**Comment by tonyskapunk** [comment]
@thebwt fixed up the typo

**Pull request merged**
